---
title: "Project Overview:"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
htmltools::tagList(rmarkdown::html_dependency_font_awesome())
```

## College Basketball Prediction Engine
####[<i class="fa fa-github fa-lg"></i> Repo](https://github.com/DavidDoesData/cbbpa)       [<i class="fa fa-youtube-play fa-lg"></i> Playlist](https://www.youtube.com/playlist?list=PLuMZyjodYY6T9WM2Opa_-vwig970tYA5_)
***

### Project Goal

This project is an attempt at making a predictive model for NCAA Div I Men's Basketball games. In addition to predicting winners, we want to predict point spreads. 

### Measuring Success
We will "bet" on games trying to pick the winner, including the spread. I will be getting spreads and odds from bet365.com. The goal is to be more than 52.4% accurate in predictions on those games. Assuming a game has a well handicapped spread, the odds for both teams will be -110. There's some math somewhere, that I should include sometime, that tells us that the break even point is 52.4% accuracy with those odds.

Success is "making money".

Failure is not "making money".

### The Data

I'm scraping it from ESPN.com. I'll need to write a web crawler/scraper to collect the data. Since I'm coding in R, I'll be using Rvest. Why? Because I know you can scrape with it. :|


```R
install.packages('rvest')
```

This is where we're looking for links to crawl: [ESPN](http://www.espn.com/mens-college-basketball/teams)

We can find the Team Ids by searching for something that looks like this:
```
/ncb/teams/stats?teamId=XXXX
```

The url structures we'll be crawling are:
```
http://www.espn.com/mens-college-basketball/team/schedule/_/id/XXXX/year/YYYY
XXXX: Team Id
YYYY: The Year
```
We need the year, so we can go back in time and grab historical results.

> **NOTE**: If a year is not in the set, it will display the 2017-18 schedule.

Psuedo code:
```
For each teamId{ 
  YEAR = 2018
  read_html = http://www.espn.com/mens-college-basketball/team/schedule/_/id/teamId/year/YEAR
  if read_html$year_on_page == YEAR{
    scrapeTheData()
    YEAR = YEAR-1
  }
}
  
```

### Let's Break Schedules Down
When did they play?
```
<td>
  Fri, Nov 10
</td>
```
> **NOTE**: The year has to be inferred from the dataset you're looking at, and the date the game was played.

We only need home games. The away games for any team will show up on the opponents pages as home games. They are identified by the following:
```
<li class="game-status">
  vs
</li>
```

Second, who are they playing?
```
<li class="team-name">
  <a href="http://www.espn.com/mens-college-basketball/team/_/id/314/iona-gaels">
    Iona
  </a>
</li>
```

Did they win? Did they lose?
```
<li class="game-status win">
<li class="game-status loss">
```

What's the score?
```
<li class="score">
  <a href="//www.espn.com/ncb/recap/_/gameId/400989985">
    69-67
  </a>
</li>
```

We need to grab the gameId from the url that's buried in the above anchor tag. We'll use it to get the box scores.


### Let's Break Down Box Scores
The url
```
http://www.espn.com/mens-college-basketball/boxscore?gameId=400989985
```

How the score by half is structured:
```
<tbody>
	<tr>
		<td class="team-name">IONA</td>
		<td>23</td>
		<td>44</td>
		<td class="final-score">67</td>
	</tr>
	<tr>
		<td class="team-name">ALBY</td>
		<td>34</td>
		<td>35</td>
		<td class="final-score">69</td>
	</tr>
</tbody>
```
There are no identifers for which half is which, we need to be careful when grabbing that information.

How the player rows are structured:
```
<tr class="">
	<td class="name" style="display: none;">
		<a name="&amp;lpos=ncb:game:boxscore:playercard" href="http://www.espn.com/mens-college-basketball/player/_/id/3907611/roland-griffin">
			<span>R. Griffin</span>
			<span class="abbr">R. Griffin</span>
		</a>
		<span class="position">F</span>
	</td>
	<td class="min" style="display: table-cell;">33</td>
	<td class="fg" style="display: table-cell;">3-6</td>
	<td class="3pt" style="display: table-cell;">0-0</td>
	<td class="ft" style="display: table-cell;">2-3</td>
	<td class="oreb" style="display: table-cell;">0</td>
	<td class="dreb" style="display: table-cell;">3</td>
	<td class="reb" style="display: table-cell;">3</td>
	<td class="ast" style="display: table-cell;">1</td>
	<td class="stl" style="display: table-cell;">1</td>
	<td class="blk" style="display: table-cell;">2</td>
	<td class="to" style="display: table-cell;">1</td>
	<td class="pf" style="display: table-cell;">2</td>
	<td class="pts" style="display: table-cell;">8</td>
</tr>
```
This is mor straightforward than the schedule page. Each \<td> has a class that is the name of the variable we are capturing. The only tricky one is the name, but it looks like we can use what's in <span class="abbr"> and we can capture the position from <span class="position">.

> **NOTE**: It's a bit difficult to keep track of the team for each table. Just be careful.

All of that information will be written to a csv, so I can munge the data later. That's the first thing that needs to happen.